version: "3.8"

services:
  api:
    build:
      context: .
      args:
        ENVIRONMENT: stg
    ports:
      - "8020:8000"
    environment:
      - ENVIRONMENT=stg
      - DEBUG=0
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2
