[tool.black]
line-length = 120
target-version = ['py313']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = ["-v", "--tb=short", "--disable-warnings"]
markers = [
  "crud: CRUD operation tests",
  "api: API endpoint tests",
  "model: Model layer tests",
  "service: Service layer tests",
  "mock: Mock-based tests",
  "integration: Integration tests",
  "slow: slow running tests",
]

[tool.ruff]
line-length = 120
ignore = ["E501", "ARG001", "F811"]
