"""add_unique_constraint_to_ssid

Revision ID: d40d73db2896
Revises: dec919eeaf10
Create Date: 2025-06-25 23:54:33.717817

"""

from typing import Sequence, Union

from alembic import op

# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d40d73db2896"
down_revision: Union[str, Sequence[str], None] = "dec919eeaf10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_ssid"), table_name="event")
    op.create_index(op.f("ix_event_ssid"), "event", ["ssid"], unique=True)
    op.drop_index(op.f("ix_person_ssid"), table_name="person")
    op.create_index(op.f("ix_person_ssid"), "person", ["ssid"], unique=True)
    op.drop_index(op.f("ix_tag_ssid"), table_name="tag")
    op.create_index(op.f("ix_tag_ssid"), "tag", ["ssid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tag_ssid"), table_name="tag")
    op.create_index(op.f("ix_tag_ssid"), "tag", ["ssid"], unique=False)
    op.drop_index(op.f("ix_person_ssid"), table_name="person")
    op.create_index(op.f("ix_person_ssid"), "person", ["ssid"], unique=False)
    op.drop_index(op.f("ix_event_ssid"), table_name="event")
    op.create_index(op.f("ix_event_ssid"), "event", ["ssid"], unique=False)
    # ### end Alembic commands ###
